default_platform(:android)

platform :android do
  desc "Builds the debug APK"
  lane :build_debug do
    gradle(task: "assembleDebug")
  end

  desc "Builds the release APK"
  lane :build_release do
    gradle(task: "assembleRelease")
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    # This lane is a placeholder. F-Droid builds from source,
    # but having this setup helps with metadata management.
    upload_to_play_store
  end
end
